version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/opt/app
    working_dir: /opt/app
  db:
    build: ./docker/db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  proxy:
    build: docker/nginx
    ports:
      - 8888:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf